### ISSUE TITLE
How to generate the test set pkl data?

### ISSUE THREAD

**Issue by rockywind** [xinzhuma/patchnet#19]
Hi,
I can't generate the test set pkl, because the test set have not the label_2 directory.

> (PCT-3D) zizhang.wu@shaxbw04:/newnfs/zzwu/08_3d_code/patchnet/tools/data_prepare$ python /newnfs/zzwu/08_3d_code/patchnet/tools/data_prepare/patch_data_prepare_adabin.py
test split patch data gen:   0%|                                                                 | 0/7518 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/newnfs/zzwu/08_3d_code/patchnet/tools/data_prepare/patch_data_prepare_adabin.py", line 349, in <module>
    whitelist = whitelist)
  File "/newnfs/zzwu/08_3d_code/patchnet/tools/data_prepare/patch_data_prepare_adabin.py", line 76, in extract_patch_data
    objects = dataset.get_label(data_idx)
  File "/newnfs/zzwu/08_3d_code/patchnet/lib/datasets/kitti_dataset_adabin.py", line 69, in get_label
    assert os.path.exists(label_file)
AssertionError

**Comment by xinzhuma** [comment]
we only provide the 2D detections for the validation set. if you can to generate the results on test set, you need to train your 2D detector first, and use your results to generate the test pkl file.
